CREATE TABLE inbox_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       VARCHAR(100) NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    event_type     VARCHAR(20)  NOT NULL,
    aggregate_type VARCHAR(20)  NOT NULL,
    received_at    TIMESTAMP    NOT NULL
);

CREATE INDEX idx_inbox_event_event_id ON inbox_event (event_id);
CREATE INDEX idx_inbox_event_aggregate_id ON inbox_event (aggregate_id);
CREATE INDEX idx_inbox_event_status ON inbox_event (received_at);
