CREATE TABLE shipment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id       VARCHAR(50) NOT NULL UNIQUE,
    sender_id       VARCHAR(50) NOT NULL,
    recipient_id    VARCHAR(50) NOT NULL,
    tracking_number VARCHAR(50) NOT NULL

);


