CREATE TABLE outbox_event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    event_type     VARCHAR(20)  NOT NULL,
    payload       TEXT         NOT NULL,
    occurred_on    TIMESTAMP WITH TIME ZONE NOT NULL,
    processed     BOOLEAN      NOT NULL DEFAULT FALSE,
    status     VARCHAR(20)  NOT NULL
);

CREATE INDEX idx_outbox_event_event_type ON outbox_event(status);

