CREATE TABLE shipment_tracking_status
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number VARCHAR(100)             NOT NULL,
    shipment_status VARCHAR(20)              NOT NULL,
    event_id        VARCHAR(100)             NOT NULL,
    occurred_on     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
